### ISSUE TITLE
wget: override robots.txt for ja.cppreference.com

### ISSUE THREAD

**Issue by myfreeer** [milkpot/cppreference-doc#1]
The <https://ja.cppreference.com/robots.txt> has changed to listed below, which makes wget to download the index page only.
Using the command-line switch `-e robots=off` would help, according to <https://unix.stackexchange.com/a/25353>.
```
User-agent: *
Disallow: /
```

**Comment by milkpot** [comment]
Fixed.
Thank you for your report.
